deployment:
  name: enlil
service:
  http:
    externalPort: 80
    internalPort: 8080

management:
  port: 9001


replicas: 1
rollingUpdate:
  maxSurge: 25%
  maxUnavailable: 25%

resources:
  memLimit: "2400Mi"
  cpuRequest: "1"
  memRequest: "2000Mi"
  xss: 1024m
  xmx: 2048m

configMapMount:
  name: enlil-config

image:
  identifier: <+artifacts.primary.image>
  imagePullPolicy: Always