common:
  app: enlil
  shortname: enlil
  team: team-ror
  ingress:
    enabled: true
    trafficType: public
  service:
    internalPort: 8080
  deployment:
    prometheus:
      enabled: true
      path: /actuator/prometheus
    replicas: 1
  container:
    image: <+artifacts.primary.image>
    cpu: 0.3
    memory: 128
    prometheus:
      enabled: true
    probes:
      enabled: true
      spec:
        startupProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 9001
          periodSeconds: 1
          timeoutSeconds: 5
          failureThreshold: 20
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 9001
          initialDelaySeconds: 0
          periodSeconds: 60
          timeoutSeconds: 30
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 9001
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 6
