apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name" . }}-application
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "labels" . | indent 4 }}
data:
  application.properties: |-
    spring.cloud.gcp.firestore.enabled=true
    spring.cloud.gcp.firestore.project-id={{ .Values.configMap.firestoreProjectId }}
    management.server.port=9001
    management.endpoints.enabled-by-default=false
    management.endpoint.info.enabled=true
    management.endpoint.health.enabled=true
    management.endpoint.health.group.liveness.show-details=always
    management.endpoint.health.group.readiness.show-details=always
    management.endpoint.prometheus.enabled=true
    management.endpoints.web.exposure.include=info,health,prometheus,env,metrics

