apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "enlil.common.labels" . | indent 4 }}
data:
  application.properties: |-
    # Firestore
    spring.cloud.gcp.firestore.enabled=true
    spring.cloud.gcp.firestore.project-id={{ .Values.configMap.firestoreProjectId }}
    {{ if (.Values.configMap.firestoreDatabaseId) }}
    spring.cloud.gcp.firestore.database-id={{ .Values.configMap.firestoreDatabaseId }}
    {{ end }}

    # Management server
    management.server.port={{ .Values.management.port }}
    management.endpoints.enabled-by-default=false
    management.endpoint.info.enabled=true
    management.endpoint.health.enabled=true
    management.endpoint.health.group.liveness.show-details=always
    management.endpoint.health.group.readiness.show-details=always
    management.endpoint.prometheus.enabled=true
    management.endpoints.web.exposure.include=info,health,prometheus,env,metrics

    # OAuth2 Resource Server
    enlil.oauth2.resourceserver.auth0.ror.claim.namespace=https://ror.entur.io/

    # OAuth2 Resource Server for Entur Partner tenant
    enlil.oauth2.resourceserver.auth0.entur.partner.jwt.issuer-uri={{ .Values.configMap.auth0.partner.url }}
    enlil.oauth2.resourceserver.auth0.entur.partner.jwt.audience={{ .Values.configMap.auth0.ror.audience }}

    # OAuth2 Resource Server for RoR tenant
    enlil.oauth2.resourceserver.auth0.ror.jwt.issuer-uri={{ .Values.configMap.auth0.ror.url }}
    enlil.oauth2.resourceserver.auth0.ror.jwt.audience={{ .Values.configMap.auth0.ror.audience }}

    # OAuth2 Entur Internal Client
    spring.security.oauth2.client.registration.internal.authorization-grant-type=client_credentials
    spring.security.oauth2.client.registration.internal.client-id={{ .Values.configMap.auth0.client.clientId }}
    spring.security.oauth2.client.provider.internal.token-uri={{ .Values.configMap.auth0.client.tokenUri }}
    ror.oauth2.client.audience={{ .Values.configMap.auth0.client.audience }}

    # Authorization
    enlil.security.role.assignment.extractor={{ .Values.configMap.roleAssignmentExtractor }}
    user.permission.rest.service.url={{ .Values.configMap.baba.service }}/services/organisations/users

    # Beans and profiles
    spring.profiles.active=entur,scheduling
    spring.main.allow-bean-definition-overriding=true
