name: Build and push
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  docker-lint:
    uses: entur/gha-docker/.github/workflows/lint.yml@v1
  maven-verify:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      # nodejs is needed because the dynamic download of it via the prettier maven plugin often
      # times out
      # Example: https://github.com/opentripplanner/OpenTripPlanner/actions/runs/4490450225/jobs/7897533439
      - uses: actions/setup-node@v4
        with:
          node-version: 18.20.8
      - uses: actions/setup-java@v4
        with:
          java-version: 21.0.1+12
          distribution: liberica
          cache: 'maven'
        env:
          GITHUB_ACTOR: ${{ secrets.ARTIFACTORY_USER }}
          GITHUB_TOKEN: ${{ secrets.ARTIFACTORY_APIKEY }}
      - run: |
          mvn verify -Dprettier.nodePath=node -Dprettier.npmPath=npm
      - run: |
          mvn \
            org.jacoco:jacoco-maven-plugin:prepare-agent verify \
            org.jacoco:jacoco-maven-plugin:report sonar:sonar \
            -P prettierSkip \
            -Dmaven.main.skip \
            -DskipTests \
            -Dsonar.projectKey=entur_enlil \
            -Dsonar.organization=enturas-github \
            -Dsonar.projectName=enlil \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${{ secrets.ENTUR_SONAR_PASSWORD }}
      - uses: actions/upload-artifact@v5.0.0
        with:
          path: target/*.jar
  docker-build:
    needs: [docker-lint, maven-verify]
    uses: entur/gha-docker/.github/workflows/build.yml@v1
    with:
      build_artifact_name: artifact
      build_artifact_path: target
  docker-push:
    if: github.repository_owner == 'entur' && github.event_name == 'push'
    needs: [docker-build]
    uses: entur/gha-docker/.github/workflows/push.yml@v1
