name: Build and push

on:
  push:
    branches:
      - master

jobs:
  docker-lint:
    uses: entur/gha-docker/.github/workflows/lint.yml@v1
  maven-verify:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21.0.1+12
          distribution: liberica
          cache: 'maven'
        env:
          GITHUB_ACTOR: ${{ secrets.ARTIFACTORY_USER }}
          GITHUB_TOKEN: ${{ secrets.ARTIFACTORY_APIKEY }}
      - run: |
          mvn verify
      - uses: actions/upload-artifact@v4.3.3
        with:
          path: target/enlil-0.0.1-SNAPSHOT.jar
  docker-build:
    needs: [docker-lint, maven-verify]
    uses: entur/gha-docker/.github/workflows/build.yml@v1
    with:
      build_artifact_name: enlil-0.0.1-SNAPSHOT.jar
      build_artifact_path: target

